[package]
name = "xonotic_name_gradient"
version = "0.1.0"
authors = ["Cameron <airedaledev@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
